-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  first_name text,
  last_name text,
  avatar_url text,
  website text,
  visited_countries text[], -- Array of country names
  passport_stamps jsonb default '[]'::jsonb -- Detailed stamp data
);

-- Set up Row Level Security (RLS)
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create a table for comments
create table comments (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  post_slug text not null,
  user_id uuid references auth.users not null,
  content text not null,
  user_email text,
  user_metadata jsonb
);

-- Set up RLS for comments
alter table comments enable row level security;

create policy "Comments are viewable by everyone."
  on comments for select
  using ( true );

create policy "Authenticated users can insert comments."
  on comments for insert
  with check ( auth.role() = 'authenticated' );

-- Set up Storage for Avatars
-- You need to create a bucket named 'avatars' in the Supabase Dashboard -> Storage
-- And set the policy to "Public" or add policies:
-- INSERT: authenticated users
-- SELECT: public
